name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Altere para a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10  # Especifique a versão do Python que você está usando

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to GitHub Pages
        run: |
          # Execute qualquer comando de implantação aqui
          # Por exemplo, você pode usar o Gunicorn para servir sua API Flask

          # Exemplo com Gunicorn:
          gunicorn -w 4 -b 0.0.0.0:5000 app:app  # Certifique-se de ajustar o comando conforme sua configuração

